# Generated by Django 3.2 on 2021-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakeoil_webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='unnamed'),
            preserve_default=False,
        ),
    ]
